name: flutter_google_maps_example
description: Demonstrates how to use the flutter_google_maps package.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_google_maps:
    path: ../
  cupertino_icons: 
  imagebutton:
  url_launcher: 
  shared_preferences:
  firebase_core: 
  cloud_firestore: 
  firebase_storage: 
  datetime_picker_formfield: 
  buddhist_datetime_dateformat: 
  fluttertoast: 
  firebase_auth: 
  image_picker: 
  # flutter_pdfview: ^1.0.
  pdf_viewer_plugin: 
  path_provider: 
  webview_flutter: 
  intl:
  http: 
  dio: 
  provider:
  # flutter_webview_plugin: 
  # flutter_inappwebview: ^5.1.0+4
  flutter_custom_clippers: 
  device_preview: 
  sizer: 
  syncfusion_flutter_pdfviewer: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/map-marker-warehouse.png
    - images/Logo_BSRU.png
    - images/BSRU.png
    - images/bsru-1.png
    - images/history-book.png
    - images/news.png
    - images/penitentiary.png
    - images/person.png
    - images/employee.png
    - images/schedule.png
    - images/22.png
    - images/information.png
    - images/map.png
    - images/66.png
    - images/file.png
    - images/contact.png
    - images/buttonBG.png
    - images/facebook.png
    - images/domain.png
    - images/footer.png
    - images/address.png
    - images/agencyOne.jpg
    - images/cropped-banner.hrmd_.jpg
    - images/cropped-web.jpg
    - images/nn.png
    - images/bv.png
    - images/gd.jpg
    - images/gw.jpg
    - images/hr.jpg
    - images/web.png
    - images/gj.png
    - images/fl.png
    - images/cc.png
    - images/y4.jpg
    - images/ej.jpg
    - images/Hard-Culture.jpg
    - images/hd.jpg
    - images/df.jpg
    - images/hp.jpg
    - images/BN.jpg
    - images/gk.jpg
    - images/pj.jpg
    - images/ui.png
    - images/histo1.png
    - images/parchment.png
    - images/BSRUhis.png
    - images/headp1.jpg
    - images/knowledge.png
    - images/BSRU1-2.jpg
    - images/executive.png
    - images/Tarbsru.jpeg
    - images/unnamed.jpg
    - images/idea.png
    - images/shuttle.png
    - images/sci.png
    - images/gradbanner.gif
    - images/elec.jpg
    - images/song.jpg
    - images/human.png
    - images/manage.png
    - images/teah.png
    - images/PopUp.png
    - images/page.jpg
    - images/hhoo.jpg
    - images/key11.png
    - images/web11.png
    - images/diagram.png
    - images/business.png
    - images/document.png
    - images/pie-chart.png
    - images/calendar.png
    - images/email.png
    - images/steering-wheel.png
    - images/search.png
    - images/seo.png
    - images/world-grid.png
    - images/television.png
    - images/bad-review.png
    - images/radio-antenna.png
    - images/certificate.png
    - images/flat.png
    - images/multimedia.png
    - images/nurse.png
    - images/sofa.png
    - images/studentNew.png
    - images/purse.png
    - images/briefcase.png
    - images/scholarship.png
    - images/employeeii.png
    - images/user.png
    - images/maps.png
    - images/ff.jpg
    - images/page_gif.gif
    - images/bsru_purple.png
    - images/admin.png
  fonts:
    - family: Pridi
      fonts:
        - asset: fonts/Pridi-Regular.ttf
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf


